name: Performance tests
on:
  push:
    branches:
      - master
      - perf-testing

jobs:
  performance_tests:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
      CDK_DEFAULT_REGION: us-west-2
      AWS_REGION: us-west-2
    defaults:
      run:
        working-directory: ./perf-cdk
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.282'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: build jmh jar
        run: RELEASE_VERSION="jmh" ./gradlew clean jmhJar
        working-directory: ./
      - run: npm install -g aws-cdk
      - run: npm install -g typescript
      - run: npm i
      - id: cdk_deploy
        run: |
          cdk deploy --require-approval never -O deploy-output.json
          echo "::set-output name=host_ip::$(jq -r .PerfCdkStack.simpleinstance1output deploy-output.json)"
      - run: echo ${{ steps.cdk_deploy.outputs.host_ip }}
      - name: Wait for ssh ready
        run: timeout 30 sh -c 'until nc -z $0 $1; do sleep 0.1; done' ${{ steps.cdk_deploy.outputs.host_ip }} 22
      - run: ls -l build/libs/graphql-java-jmh.jar
        working-directory: ./
      - name: Copy jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ steps.cdk_deploy.outputs.host_ip }}
          username: ec2-user
          key: ${{ secrets.EC2_USER_KEY }}
          port: 22
          source: "build/libs/graphql-java-jmh.jar"
          target: "~"
          strip_components: 2
      - name: Run JMH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.cdk_deploy.outputs.host_ip }}
          username: ec2-user
          key: ${{ secrets.EC2_USER_KEY }}
          port: 22
          command_timeout: 240m
          script: |
            pwd
            ls -l
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            curl -s "https://get.sdkman.io" | bash
            source "/home/ec2-user/.sdkman/bin/sdkman-init.sh"
            sdk install java 11.0.11.hs-adpt
            java -version
            echo "java -jar graphql-java-jmh.jar -rf json"
            echo "test" > jmh-result.json
            ls -l
            cat jmh-result.json
            aws s3 cp jmh-result.json s3://graphql-java-perf-tests/jmh-results/jmh-${{ github.sha }}-jdk11-$(date --iso-8601=seconds).json
      - run: cdk destroy -f

